name: Generate ASCII Artwork
on:
  workflow_dispatch:

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install cowsay -y
      - name: Generate ASCII dragon
        run: cowsay -f dragon "Run for cover, I am a DRAGON.... RAWR" > dragon.txt
      - name: Pause for 30 seconds
        run: sleep 30
      - name: Upload dragon.txt as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dragon-artifact
          path: dragon.txt

  test_job_2:
    runs-on: ubuntu-latest
    needs: build_job_1
    steps:
      - name: Pause for 10 seconds
        run: sleep 10
      - name: Download dragon.txt artifact
        uses: actions/download-artifact@v3
        with:
          name: dragon-artifact
      - name: Verify dragon.txt
        run: grep -i "dragon" dragon.txt

  deploy_job_3:
    runs-on: ubuntu-latest
    needs: build_job_1
    steps:
      - name: Download dragon.txt artifact
        uses: actions/download-artifact@v3
        with:
          name: dragon-artifact
      - name: Display dragon.txt
        run: cat dragon.txt
      - name: Simulate deployment
        run: echo "Deploying dragon.txt..."