name: Composite Action Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use my composite action
        uses: bhushan-s-pathak/azure-gitops/.github/actions/my-composite-action@main
        with:
          node-version: '18'
