name: Concurrency Two Jobs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.event.inputs.env }}
      cancel-in-progress: true
    steps:
      - name: Build Step
        run: |
          echo "🚀 Starting build for ${{ github.event.inputs.env }}"
          sleep 60
          echo "✅ Build completed for ${{ github.event.inputs.env }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build   # deploy waits for build
    concurrency:
      group: deploy-${{ github.event.inputs.env }}
      cancel-in-progress: true
    steps:
      - name: Deploy Step
        run: |
          echo "🚀 Deploying to ${{ github.event.inputs.env }}"
          sleep 60
          echo "✅ Deployment completed for ${{ github.event.inputs.env }}"
