name: Concurrency Two Jobs

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: "Environment (dev/staging/prod)"
        required: true
        default: "dev"
        options:
          - dev
          - staging
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.event.inputs.env }}
      cancel-in-progress: true
    timeout-minutes: 1
    steps:
      - name: Build Step
        run: |
          echo "🚀 Starting build for ${{ github.event.inputs.env }}"
          sleep 600
          echo "✅ Build completed for ${{ github.event.inputs.env }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: deploy-${{ github.event.inputs.env }}
      cancel-in-progress: false
    steps:
      - name: Deploy Step
        run: |
          echo "🚀 Deploying to ${{ github.event.inputs.env }}"
          sleep 600
          echo "✅ Deployment completed for ${{ github.event.inputs.env }}"
