name: Get a random joke

on:
  workflow_dispatch:

jobs:
  get-joke:
    runs-on: linuxvm1g1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get a random joke
        run: |
          python3 random_joke.py
